version: "3.9"
services:
    bot:
        build: .
        container_name: dnd-bot
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        external: false
