version: "3.9"
services:
    bot:
        build: .
        container_name: dnd-bot
        links:
            - redis
        depends_on:
            - redis
    redis:
        image: redis
        volumes:
            - redis_data:/data
    mongo:
        image: mongo
        volumes:
            - mongo_data:/data/db

volumes:
    redis_data:
        external: false
    mongo_data:
        external: false
