version: "3.9"
services:
    bot:
        build: .
        container_name: dnd-bot
        links:
            - mongo
        depends_on:
            - mongo
        network_mode: service:mongo
        environment:
            - MONGODB_URI=mongodb://mongo:27017
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        external: false
