# fly.toml file generated for dnd-bot on 2022-10-15T16:24:48-04:00

app = "dnd-bot"
kill_signal = "SIGTERM"
kill_timeout = 3

[build]
  image = "dragid10/dnd-bot"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"

[env]
  LOG_LEVEL = "debug"
  alertTime = "12"
  campaignName = "Journey to the Center of the Earth Kingdom"
  campaignAlias = "JTCEK"
  discordVC = "Party"

[services]