# fly.toml file generated for dnd-bot on 2022-10-15T16:24:48-04:00

app = "dnd-bot"
kill_signal = "SIGTERM"
kill_timeout = 3

[build]
  image = "dragid10/dnd-bot"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"

[services]